"""
Proactive Insight Models.

Phase 16c: Practice AI - Proactive Intelligence

Models for AI-generated insights and suggestions.
"""

import uuid
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Any

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel

if TYPE_CHECKING:
    from app.models.clinic import Clinic
    from app.models.doctor import Doctor
    from app.models.patient import Patient
    from app.models.user import User


class InsightType(str, Enum):
    """Types of proactive insights."""

    FOLLOWUP_DUE = "followup_due"
    SCHEDULE_GAP = "schedule_gap"
    REVENUE_ALERT = "revenue_alert"
    NO_SHOW_RISK = "no_show_risk"
    PROCEDURE_ANOMALY = "procedure_anomaly"
    WAITLIST_OPPORTUNITY = "waitlist_opportunity"
    PATIENT_ENGAGEMENT = "patient_engagement"
    DAILY_DIGEST = "daily_digest"


class InsightPriority(int, Enum):
    """Priority levels for insights (1-5)."""

    LOW = 1
    MEDIUM = 2
    MODERATE = 3
    HIGH = 4
    URGENT = 5


class ProactiveInsight(BaseModel):
    """
    Proactive insights generated by AI assistant.

    Examples:
    - "Mrs. Patel is due for follow-up after stent (7 days post-procedure)"
    - "Schedule gap: 2:00-3:00 PM available for waitlist patients"
    - "Revenue 30% below average for Tuesday"
    - "Mr. Kumar has 60% no-show rate - send reminder"
    """

    __tablename__ = "proactive_insights"

    # Core Relations
    clinic_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("clinics.id"),
        nullable=False,
        index=True,
    )
    patient_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("patients.id"),
        nullable=True,
        index=True,
    )
    doctor_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("doctors.id"),
        nullable=True,
        index=True,
    )

    # Insight Details
    insight_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )
    priority: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=InsightPriority.MEDIUM.value,
        index=True,
    )

    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # Suggested Action (JSON format for one-click execution)
    # Example: {"action": "book_appointment", "patient_id": "...", "slot": "..."}
    suggested_action: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
    )

    # Metadata
    metadata: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
    )

    # Expiration
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
    )

    # User Actions
    dismissed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    dismissed_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=True,
    )

    acted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    acted_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=True,
    )

    # Relationships
    clinic: Mapped["Clinic"] = relationship("Clinic")
    patient: Mapped["Patient | None"] = relationship("Patient")
    doctor: Mapped["Doctor | None"] = relationship("Doctor")
    dismissed_by: Mapped["User | None"] = relationship(
        "User",
        foreign_keys=[dismissed_by_id],
    )
    acted_by: Mapped["User | None"] = relationship(
        "User",
        foreign_keys=[acted_by_id],
    )

    def __repr__(self) -> str:
        return f"<ProactiveInsight {self.insight_type}: {self.title} (P{self.priority})>"


class FollowupSchedule(BaseModel):
    """
    Follow-up schedules based on procedure rules.

    Automatically generated when procedures are recorded.
    """

    __tablename__ = "followup_schedules"

    # Core Relations
    clinic_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("clinics.id"),
        nullable=False,
        index=True,
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("patients.id"),
        nullable=False,
        index=True,
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("doctors.id"),
        nullable=False,
        index=True,
    )
    procedure_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("procedures.id"),
        nullable=False,
        index=True,
    )

    # Follow-up Details
    due_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
    )
    reason: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    priority: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=InsightPriority.MEDIUM.value,
    )

    # Notification Tracking
    notified_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Completion Tracking
    completed: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        index=True,
    )
    scheduled_appointment_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("appointments.id"),
        nullable=True,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Relationships
    clinic: Mapped["Clinic"] = relationship("Clinic")
    patient: Mapped["Patient"] = relationship("Patient")
    doctor: Mapped["Doctor"] = relationship("Doctor")
    procedure: Mapped["Procedure"] = relationship("Procedure")

    def __repr__(self) -> str:
        return f"<FollowupSchedule {self.reason} due {self.due_date.date()}>"


class UserDigestPreferences(BaseModel):
    """
    User preferences for daily digest delivery.
    """

    __tablename__ = "user_digest_preferences"

    # Core Relations
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=False,
        unique=True,
        index=True,
    )
    clinic_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("clinics.id"),
        nullable=False,
        index=True,
    )

    # Preferences
    enabled: Mapped[bool] = mapped_column(
        Boolean,
        default=True,
    )
    delivery_hour: Mapped[int] = mapped_column(
        Integer,
        default=8,  # 8 AM
    )
    delivery_minute: Mapped[int] = mapped_column(
        Integer,
        default=0,
    )

    # Channels (JSON array: ["push", "email", "sms"])
    channels: Mapped[list[str]] = mapped_column(
        JSONB,
        default=["push"],
    )

    # Content Filters
    include_revenue: Mapped[bool] = mapped_column(Boolean, default=True)
    include_appointments: Mapped[bool] = mapped_column(Boolean, default=True)
    include_followups: Mapped[bool] = mapped_column(Boolean, default=True)
    include_schedule_gaps: Mapped[bool] = mapped_column(Boolean, default=True)
    include_waitlist: Mapped[bool] = mapped_column(Boolean, default=True)

    # Relationships
    user: Mapped["User"] = relationship("User")
    clinic: Mapped["Clinic"] = relationship("Clinic")

    def __repr__(self) -> str:
        return f"<UserDigestPreferences user={self.user_id} enabled={self.enabled}>"
